/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jamarfal_instagramndk_MainActivity */

#ifndef _Included_com_jamarfal_instagramndk_MainActivity
#define _Included_com_jamarfal_instagramndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jamarfal_instagramndk_MainActivity_REQUEST_IMAGE_CAPTURE
#define com_jamarfal_instagramndk_MainActivity_REQUEST_IMAGE_CAPTURE 1L
/*
 * Class:     com_jamarfal_instagramndk_MainActivity
 * Method:    convertImageToGreyScale
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_jamarfal_instagramndk_MainActivity_convertImageToGreyScale
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_jamarfal_instagramndk_MainActivity
 * Method:    convertImageToSepia
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_jamarfal_instagramndk_MainActivity_convertImageToSepia
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_jamarfal_instagramndk_MainActivity
 * Method:    addFrameToImage
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_jamarfal_instagramndk_MainActivity_addFrameToImage
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_jamarfal_instagramndk_MainActivity
 * Method:    convertImageToSobel
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_jamarfal_instagramndk_MainActivity_convertImageToSobel
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
